apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
    name: ingress-service
    annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/use-regex: 'true'
        nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
    rules:
        - http:
              paths: 
                  - path: /ssrf
                    backend:
                          serviceName: ssrf-cluster-ip-service
                          servicePort: 2640

