apiVersion: apps/v1
kind: Deployment
metadata:
    name: jailed-deployment
    labels:
        component: jailed
spec:
    replicas: 5
    selector:
        matchLabels:
            component: jailed
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxSurge: 1
            maxUnavailable: 0
    template:
        metadata:
            labels:
                component: jailed
        spec:
            containers:
                - name: jailed
                  image: aryan9600/ieeectf-jailed
