apiVersion: v1
kind: Service
metadata:
    name: jail-cluster-ip-service
spec:
    type: ClusterIP
    selector:
        component: jail
    ports:
        - protocol: TCP
          port: 9002
          targetPort: 9002
