apiVersion: v1
kind: Service
metadata:
    name: jailed-cluster-ip-service
spec:
    type: ClusterIP
    selector:
        component: jailed
    ports:
        - protocol: TCP
          port: 9003
          targetPort: 22
