apiVersion: v1
kind: Service
metadata:
    name: node-vm-cluster-ip-service.yaml
spec:
    type: ClusterIP
    selector:
        component: node-vm
    ports:
        - port: 4000
          targetPort: 2640
