apiVersion: apps/v1
kind: Deployment
metadata:
    name: node-vm-deployment
    labels:
        component: node-vm
spec:
    replicas: 3
    selector:
        matchLabels:
            component: node-vm
    template:
        metadata:
            labels:
                component: node-vm
        spec:
            containers:
                - name: node-vm
                  image: aryan9600/ieeectf-nodejs-vm
                  resources:
                        limits:
                            cpu: "0.4"
                            memory: "300Mi"
                        requests:
                            cpu: "0.2"
                            memory: "200Mi"
