apiVersion: apps/v1
kind: Deployment
metadata:
    name: php-deployment
    labels:
        component: php-server
spec:
    replicas: 3
    selector:
        matchLabels:
            component: php-server
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxSurge: 1
            maxUnavailable: 0
    template:
        metadata:
            labels:
                component: php-server
        spec:
            containers:
                - name: php-server
                  image: aryan9600/ieeectf-haunted
                  ports:
                    - containerPort: 80
                  env:
                        - name: MYSQL_HOST
                          value: mysql-cluster-ip-service
