apiVersion: v1
kind: Service
metadata:
    name: pwn-cluster-ip-service
spec:
    type: ClusterIP
    selector:
        component: pwn
    ports:
        - protocol: TCP
          port: 9000
          targetPort: 9000
