apiVersion: apps/v1
kind: Deployment
metadata:
    name: pwn-deployment
    labels:
        component: pwn
spec:
    replicas: 5
    selector:
        matchLabels:
            component: pwn
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxSurge: 1
            maxUnavailable: 0
    template:
        metadata:
            labels:
                component: pwn
        spec:
            containers:
                - name: pwn
                  image: aryan9600/ieeectf-pwn
                  securityContext:
                      privileged: true
