apiVersion: apps/v1
kind: Deployment
metadata:
    name: ssrf-deployment
    labels:
        component: ssrf
spec:
    replicas: 3
    selector:
        matchLabels:
            component: ssrf
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxSurge: 1
            maxUnavailable: 0
    template:
        metadata:
            labels:
                component: ssrf
        spec:
            containers:
                - name: ssrf
                  image: aryan9600/ieeectf-ssrf
        
