apiVersion: v1
kind: Service
metadata:
    name: advertisment-auth-cluster-ip-service
spec:
    type: ClusterIP
    selector:
        component: advertisment-auth
    ports:
        - port: 3000
          targetPort: 3000
