version: "3.2"
services:
  php:
    build: './php/'
    volumes:
      - ./hello/:/var/www/html/hello/
  apache:
    build: './apache/'
    depends_on:
      - php
      - mysql
    ports:
      - "8080:80"
    volumes:
      - ./hello/:/var/www/html/hello/
  mysql:
    image: mysql:5.6.40
    environment:
      - MYSQL_ROOT_PASSWORD=ieeeroot
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=mashlog_demo
    ports:
        - "3306:3306"
