version: "3.2"
services:
  php:
    build: './php/'
    networks:
      - backend
    volumes:
      - ./hello/:/var/www/html/hello/
  apache:
    build: './apache/'
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "8080:80"
    volumes:
      - ./hello/:/var/www/html/hello/
  mysql:
    image: mysql:5.6.40
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
networks:
  frontend:
  backend:
